apiVersion: v1
kind: Pod

metadata:
  name: fixed-pod

spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo hello > /data/file.txt && sleep 3600"]

    volumeMounts:
    - name: data-volume
      mountPath: /data

  volumes:
  - name: data-volume
    emptyDir: {}
